excluded:
  - Carthage
  - Pods
  - LentaTests
  - LentaUITests
  - LentaSnapShotTests

identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
 #   - URL
#    - GlobalAPIKey
